from typing import Any, Protocol

class DemoRepository(Protocol):
    def list_customers(self, limit: int, offset: int) -> list[dict[str, Any]]: ...
    def get_customer(self, user_id: int) -> dict[str, Any] | None: ...
    def search_customers(self, query: str) -> list[dict[str, Any]]: ...
    def list_cards(
        self,
        card_type: str | None = None,
        min_amount: float | None = None,
        max_amount: float | None = None,
    ) -> list[dict[str, Any]]: ...
    def get_card(self, card_id: int) -> dict[str, Any] | None: ...
    def list_customer_cards(self, user_id: int) -> list[dict[str, Any]]: ...
    def list_card_transactions(
        self,
        card_id: int,
        date_from: str | None = None,
        date_to: str | None = None,
        operation_type: str | None = None,
        limit: int | None = None,
    ) -> list[dict[str, Any]]: ...
    def list_customer_transactions(
        self,
        user_id: int,
        date_from: str | None = None,
        date_to: str | None = None,
        operation_type: str | None = None,
        limit: int = 50,
    ) -> list[dict[str, Any]]: ...
    def list_transactions(self, filters: dict[str, Any]) -> list[dict[str, Any]]: ...
    def get_transaction(self, transaction_id: str) -> dict[str, Any] | None: ...
    def count_customers(self) -> int: ...
    def count_cards(self, card_type: str | None = None) -> int: ...
    def count_transactions(self, filters: dict[str, Any]) -> int: ...
    def count_users_with_transactions(self, filters: dict[str, Any]) -> int: ...
    def users_with_transactions(self, filters: dict[str, Any]) -> list[dict[str, Any]]: ...
    def transaction_amount(self, aggregate: str, filters: dict[str, Any]) -> float: ...
    def transaction_extreme(self, direction: str, operation_type: str | None = None) -> dict[str, Any] | None: ...
    def transactions_by_date(self, filters: dict[str, Any]) -> list[dict[str, Any]]: ...
    def transactions_by_operation_type(self) -> list[dict[str, Any]]: ...
    def cards_by_type(self) -> list[dict[str, Any]]: ...
    def cards_balance(self, aggregate: str, card_type: str | None = None) -> float: ...
    def user_summary(self, user_id: int) -> dict[str, Any] | None: ...
    def user_transaction_amount(self, user_id: int, operation_type: str, filters: dict[str, Any]) -> float: ...
    def ranking_users(self, operation_type: str, filters: dict[str, Any], limit: int) -> list[dict[str, Any]]: ...
    def ranking_cards_by_balance(self, card_type: str | None, limit: int) -> list[dict[str, Any]]: ...
